// Command sembed validates the Matrix Sentry engine on real semantic embeddings
// generated by Ollama (nomic-embed-text, 768-dim). It replaces synthetic SIFT
// vectors with actual text embeddings from a diverse corpus to prove the thesis
// holds on production-realistic data:
//
//  1. Download/load a text corpus (public domain literature + technical text)
//  2. Embed via Ollama HTTP API (batched)
//  3. Compute brute-force exact kNN ground truth
//  4. Run flat PQ + IVFADC + nprobe sweep
//  5. Report recall/latency/compression — directly comparable to SIFT results
//
// Usage:
//
//	go run ./cmd/sembed -dir /data/sembed -ollama http://localhost:11434
package main

import (
	"bufio"
	"bytes"
	"encoding/binary"
	"encoding/json"
	"flag"
	"fmt"
	"math"
	"net/http"
	"os"
	"path/filepath"
	"runtime"
	"sort"
	"strings"
	"sync"
	"time"

	"matrixsentry/ivf"
	"matrixsentry/pq"
)

// --- configuration ---

const (
	embDim       = 768
	defaultModel = "nomic-embed-text"
)

func main() {
	dir := flag.String("dir", "/data/sembed", "working directory for cached embeddings")
	ollamaURL := flag.String("ollama", "http://localhost:11434", "Ollama API base URL")
	model := flag.String("model", defaultModel, "embedding model name")
	nlist := flag.Int("nlist", 64, "coarse cells for IVFADC")
	M := flag.Int("m", 96, "PQ subspaces (768 / 96 = 8-dim per sub, like SIFT's 128/8=16)")
	K := flag.Int("k", 256, "centroids per subspace")
	iter := flag.Int("iter", 25, "k-means iterations")
	nprobeCSV := flag.String("nprobe", "1,4,8,16,32", "comma-separated nprobe sweep")
	batchSize := flag.Int("batch", 64, "Ollama embedding batch size")
	maxBase := flag.Int("maxbase", 5000, "max base vectors (0 = all)")
	maxQuery := flag.Int("maxquery", 500, "max query vectors (0 = all)")
	corpusDir := flag.String("corpus", "", "directory with .txt files for corpus (default: <dir>/corpus)")
	emit := flag.String("emit", "", "if set, also write <dir>/<emit>_{base,learn,query}.fvecs + <emit>_groundtruth.ivecs (SIFT layout) for ivfsweep/ivfpredict")
	flag.Parse()

	os.MkdirAll(*dir, 0755)

	fmt.Printf("== Matrix Sentry · Scenario B: Real Embeddings (%d cores) ==\n", runtime.GOMAXPROCS(0))
	fmt.Printf("model=%s  dim=%d  M=%d  K=%d  nlist=%d\n\n", *model, embDim, *M, *K, *nlist)

	// --- Phase 1: corpus + embed ---
	basePath := filepath.Join(*dir, "base.fvecs")
	queryPath := filepath.Join(*dir, "query.fvecs")
	baseTextsPath := filepath.Join(*dir, "base_texts.txt")
	queryTextsPath := filepath.Join(*dir, "query_texts.txt")

	var baseVecs, queryVecs [][]float32
	var baseTexts, queryTexts []string

	if fileExists(basePath) && fileExists(queryPath) {
		fmt.Println("[cache] Loading cached embeddings from disk...")
		baseVecs = readFvecs(basePath)
		queryVecs = readFvecs(queryPath)
		if fileExists(baseTextsPath) {
			baseTexts = readLines(baseTextsPath)
		}
		if fileExists(queryTextsPath) {
			queryTexts = readLines(queryTextsPath)
		}
		fmt.Printf("  base=%d  query=%d  (cached)\n", len(baseVecs), len(queryVecs))
	} else {
		fmt.Println("[corpus] Building text corpus...")
		cdir := *corpusDir
		if cdir == "" {
			cdir = filepath.Join(*dir, "corpus")
		}
		corpus := buildCorpus(cdir)
		fmt.Printf("  total paragraphs: %d\n", len(corpus))

		// Split: first maxQuery are queries, rest are base
		if *maxQuery > len(corpus)/5 {
			*maxQuery = len(corpus) / 5
		}
		queryTexts = corpus[:*maxQuery]
		baseCorpus := corpus[*maxQuery:]
		if *maxBase > 0 && *maxBase < len(baseCorpus) {
			baseCorpus = baseCorpus[:*maxBase]
		}
		baseTexts = baseCorpus

		fmt.Printf("  base texts: %d  query texts: %d\n", len(baseTexts), len(queryTexts))

		fmt.Println("\n[embed] Generating embeddings via Ollama...")
		t0 := time.Now()
		baseVecs = embedTexts(*ollamaURL, *model, baseTexts, *batchSize, "base")
		queryVecs = embedTexts(*ollamaURL, *model, queryTexts, *batchSize, "query")
		fmt.Printf("  embedding time: %v\n", time.Since(t0).Round(time.Millisecond))

		// Cache to disk
		writeFvecs(basePath, baseVecs)
		writeFvecs(queryPath, queryVecs)
		writeLines(baseTextsPath, baseTexts)
		writeLines(queryTextsPath, queryTexts)
		fmt.Println("  cached to disk for reuse")
	}

	if *maxBase > 0 && *maxBase < len(baseVecs) {
		baseVecs = baseVecs[:*maxBase]
	}
	if *maxQuery > 0 && *maxQuery < len(queryVecs) {
		queryVecs = queryVecs[:*maxQuery]
	}

	nBase := len(baseVecs)
	nQuery := len(queryVecs)
	dim := len(baseVecs[0])
	fmt.Printf("\nbase=%d  query=%d  dim=%d\n", nBase, nQuery, dim)
	fmt.Printf("raw size: %.1f MB  (base only, float32)\n", float64(nBase*dim*4)/(1024*1024))

	// --- Phase 2: brute-force ground truth ---
	fmt.Println("\n[ground truth] Computing exact kNN (brute-force L2)...")
	t1 := time.Now()
	gt := bruteForceKNN(queryVecs, baseVecs, 100)
	fmt.Printf("  ground truth computed: %v  (top-100 for %d queries)\n", time.Since(t1).Round(time.Millisecond), nQuery)

	// Emit the dataset in SIFT/TEXMEX layout so the access-driven harnesses
	// (ivfsweep / ivfpredict) run on REAL embeddings unchanged. learn = base
	// (single corpus: the coarse+PQ geometry trains on the base set itself).
	if *emit != "" {
		p := func(name string) string { return filepath.Join(*dir, *emit+"_"+name) }
		writeFvecs(p("base.fvecs"), baseVecs)
		writeFvecs(p("learn.fvecs"), baseVecs)
		writeFvecs(p("query.fvecs"), queryVecs)
		writeIvecs(p("groundtruth.ivecs"), gt)
		fmt.Printf("[emit] wrote %s_{base,learn,query}.fvecs + %s_groundtruth.ivecs  (%d base, %d query, dim %d)\n",
			*emit, *emit, nBase, nQuery, dim)
	}

	// Show a few semantic examples if texts available
	if len(baseTexts) > 0 && len(queryTexts) > 0 {
		fmt.Println("\n[semantic examples] Top-3 nearest for first 3 queries:")
		for qi := 0; qi < 3 && qi < len(queryTexts); qi++ {
			fmt.Printf("\n  Q%d: %q\n", qi, truncStr(queryTexts[qi], 80))
			for k := 0; k < 3 && k < len(gt[qi]); k++ {
				bi := gt[qi][k]
				fmt.Printf("    #%d (id=%d): %q\n", k+1, bi, truncStr(baseTexts[bi], 80))
			}
		}
	}

	// --- Phase 3: flat PQ baseline ---
	fmt.Printf("\n-- flat PQ (M=%d K=%d, full scan, compression=%.0fx) --\n", *M, *K, float64(dim*4)/float64(*M))
	flatQ, err := pq.New(dim, *M, *K)
	if err != nil {
		panic(err)
	}
	// Use base vectors as training set (small enough)
	t2 := time.Now()
	if err := flatQ.Train(baseVecs, *iter, 1); err != nil {
		panic(err)
	}
	fmt.Printf("  PQ train: %v\n", time.Since(t2).Round(time.Millisecond))
	codes := flatQ.EncodeBatch(baseVecs)

	for _, R := range []int{1, 10, 100} {
		t := time.Now()
		res := flatQ.SearchBatch(queryVecs, codes, R)
		dur := time.Since(t)
		r1, inter := scorePQ(res, gt, R)
		fmt.Printf("  flat  recall1@%-3d %.4f  inter@%-3d %.4f  %6.3f ms/q  (scan 100.0%%)\n",
			R, r1, R, inter, msPerQuery(dur, nQuery))
	}

	// --- Phase 4: IVFADC + nprobe sweep ---
	nprobes := parseInts(*nprobeCSV)
	if *nlist > nBase/10 {
		*nlist = nBase / 10
		if *nlist < 4 {
			*nlist = 4
		}
	}
	fmt.Printf("\n-- IVFADC (nlist=%d, M=%d K=%d) --\n", *nlist, *M, *K)
	t3 := time.Now()
	cfg := ivf.Config{Dim: dim, Nlist: *nlist, M: *M, K: *K, Iter: *iter, Seed: 1}
	ix, err := ivf.New(cfg)
	if err != nil {
		panic(err)
	}
	if err := ix.Train(baseVecs); err != nil {
		panic(err)
	}
	fmt.Printf("  train: %v\n", time.Since(t3).Round(time.Millisecond))
	t4 := time.Now()
	addResults := ix.Add(baseVecs)
	fmt.Printf("  add %d vectors: %v\n", nBase, time.Since(t4).Round(time.Millisecond))

	// Build hash→baseIndex map for IVF scoring
	hashToIdx := make(map[uint64]int, nBase)
	for i, ar := range addResults {
		if ar.Status == ivf.Inserted {
			hashToIdx[ar.Handle.Hash] = i
		}
	}
	fmt.Printf("  unique vectors: %d  (deduped: %d)\n\n", len(hashToIdx), nBase-len(hashToIdx))

	fmt.Printf("%-7s %-12s %-12s %-13s %-11s %-10s\n", "nprobe", "recall1@1", "recall1@10", "recall1@100", "inter@100", "ms/q  scan%")
	for _, np := range nprobes {
		var r1at1, r1at10, r1at100, inter100, msq float64
		var scanPct float64
		for _, R := range []int{1, 10, 100} {
			t := time.Now()
			res := ix.SearchBatch(queryVecs, np, R)
			dur := time.Since(t)
			r1, inter := scoreIVFResults(res, gt, R, hashToIdx)
			switch R {
			case 1:
				r1at1 = r1
			case 10:
				r1at10 = r1
			case 100:
				r1at100, inter100, msq = r1, inter, msPerQuery(dur, nQuery)
				scanPct = float64(np) / float64(*nlist) * 100
			}
		}
		fmt.Printf("%-7d %-12.4f %-12.4f %-13.4f %-11.4f %6.3f %5.1f%%\n",
			np, r1at1, r1at10, r1at100, inter100, msq, scanPct)
	}

	// --- Phase 5: summary ---
	compressedBytes := *M // bytes per vector after PQ
	rawBytes := dim * 4
	fmt.Printf("\n-- Summary --\n")
	fmt.Printf("  Dimension:    %d (nomic-embed-text)\n", dim)
	fmt.Printf("  Compression:  %dx (%d B → %d B per vector)\n", rawBytes/compressedBytes, rawBytes, compressedBytes)
	fmt.Printf("  Base vectors: %d\n", nBase)
	fmt.Printf("  Query vectors: %d\n", nQuery)
	fmt.Printf("  Raw base size: %.1f MB → Compressed: %.1f KB\n",
		float64(nBase*rawBytes)/(1024*1024),
		float64(nBase*compressedBytes)/1024)
}

// --- corpus builder ---

func buildCorpus(corpusDir string) []string {
	var paragraphs []string

	// First: load paragraphs from every .txt in the corpus dir (Project Gutenberg
	// books etc.), in deterministic order so the dataset is reproducible.
	matches, _ := filepath.Glob(filepath.Join(corpusDir, "*.txt"))
	sort.Strings(matches)
	for _, path := range matches {
		paras := extractParagraphs(path, 50, 500)
		fmt.Printf("  [book] %s: %d paragraphs\n", filepath.Base(path), len(paras))
		paragraphs = append(paragraphs, paras...)
	}

	// Then: add curated technical texts for domain diversity
	softwareTexts := []string{
		"A hash table provides O(1) average-case lookup by mapping keys through a hash function to array indices. Collisions are typically handled via chaining or open addressing.",
		"Garbage collection automatically reclaims memory that is no longer referenced by the program. Mark-and-sweep is the simplest algorithm: mark all reachable objects, then sweep unmarked ones.",
		"The CAP theorem states that a distributed data store can provide at most two of three guarantees: consistency, availability, and partition tolerance.",
		"A B-tree is a self-balancing tree data structure that maintains sorted data and allows searches, sequential access, insertions, and deletions in logarithmic time.",
		"Microservices architecture decomposes applications into small, independently deployable services that communicate over the network, typically using REST or gRPC.",
		"Docker containers package an application with all its dependencies into a standardized unit, using Linux kernel features like namespaces and cgroups for isolation.",
		"Git uses a directed acyclic graph to track the history of commits. Each commit points to its parent and a tree object that represents the repository state.",
		"TCP guarantees reliable, ordered delivery of a stream of bytes between applications through sequence numbers, acknowledgments, and retransmission.",
		"The actor model is a mathematical model of concurrent computation where actors are the universal primitives: they can receive messages, make decisions, create new actors, and send messages.",
		"Raft is a consensus algorithm designed for managing a replicated log. It decomposes the problem into leader election, log replication, and safety.",
		"A write-ahead log records all modifications to a database before they are applied to the data files, ensuring atomicity and durability even after a crash.",
		"Load balancing distributes network traffic across multiple servers to ensure no single server bears too much demand, improving responsiveness and availability.",
		"An inverted index maps content terms to their locations in a database, enabling full-text search. It is the foundational data structure behind search engines.",
		"Rate limiting controls the number of requests a client can make to a service within a time window, protecting against abuse and ensuring fair resource allocation.",
		"Circuit breakers prevent cascading failures in distributed systems by detecting failures and temporarily stopping requests to a failing service.",
		"Consistent hashing minimizes key remapping when nodes are added or removed from a distributed hash table, making it ideal for distributed caching systems.",
		"Event sourcing stores all changes to application state as a sequence of events, which can be replayed to reconstruct any past state of the system.",
		"A bloom filter is a space-efficient probabilistic data structure that tests whether an element is a member of a set, with possible false positives but no false negatives.",
		"Connection pooling reuses database connections across multiple requests instead of opening a new connection for each request, significantly reducing latency.",
		"Blue-green deployment maintains two identical production environments. Traffic is switched from the current version to the new one, allowing instant rollback if issues arise.",
	}

	// Domain 2: Mathematics and physics
	mathTexts := []string{
		"The fundamental theorem of calculus establishes the relationship between differentiation and integration, stating that integration can be reversed by differentiation.",
		"Eigenvalues and eigenvectors characterize linear transformations: an eigenvector's direction is unchanged by the transformation, only scaled by its eigenvalue.",
		"The Fourier transform decomposes a function of time into its constituent frequencies, transforming the signal from time domain to frequency domain.",
		"Entropy in information theory measures the average amount of information produced by a stochastic source of data, quantified in bits per symbol.",
		"Maxwell's equations describe how electric and magnetic fields are generated by charges, currents, and changes of the fields. They form the foundation of classical electromagnetism.",
		"The central limit theorem states that the sum of many independent random variables tends toward a normal distribution, regardless of the shape of the original distribution.",
		"Gradient descent iteratively moves toward a minimum of a function by taking steps proportional to the negative of the gradient at the current point.",
		"A Markov chain is a stochastic process where the probability of each state depends only on the immediately preceding state, not on the sequence of states that preceded it.",
		"The traveling salesman problem asks for the shortest possible route that visits each city exactly once and returns to the origin city. It is NP-hard.",
		"Bayes' theorem describes the probability of an event based on prior knowledge of conditions related to the event. It inverts conditional probabilities.",
		"The law of large numbers states that as a sample size grows, its mean gets closer to the average of the whole population.",
		"Singular value decomposition factorizes a matrix into three matrices, revealing the geometric structure of the original transformation in terms of stretching and rotation.",
		"The Navier-Stokes equations describe the motion of viscous fluid substances and arise from applying Newton's second law to fluid motion.",
		"Gödel's incompleteness theorems demonstrate that any consistent formal system capable of expressing arithmetic contains true statements that cannot be proved within the system.",
		"Monte Carlo methods use random sampling to obtain numerical results for problems that might be deterministic in principle but intractable to solve analytically.",
		"A tensor is a mathematical object that generalizes scalars, vectors, and matrices to higher dimensions, transforming according to specific rules under coordinate changes.",
		"The Riemann hypothesis conjectures that all non-trivial zeros of the Riemann zeta function have a real part equal to one half.",
		"Lagrangian mechanics reformulates classical mechanics using the principle of least action, expressing equations of motion through generalized coordinates and the Lagrangian.",
		"Topology studies properties of geometric objects that are preserved under continuous deformations such as stretching and bending, but not tearing or gluing.",
		"The butterfly effect refers to the sensitive dependence on initial conditions in chaotic systems, where a small change can lead to drastically different outcomes.",
	}

	// Domain 3: Biology and medicine
	bioTexts := []string{
		"DNA replication is the biological process of producing two identical replicas of DNA from one original DNA molecule, occurring during cell division.",
		"CRISPR-Cas9 is a genome editing tool that allows researchers to alter DNA sequences and modify gene function by guiding the Cas9 protein to cut DNA at a specific location.",
		"Mitochondria are organelles found in eukaryotic cells that generate most of the cell's supply of adenosine triphosphate through oxidative phosphorylation.",
		"Antibiotics work by interfering with essential processes in bacteria, such as cell wall synthesis, protein production, or DNA replication, without harming human cells.",
		"The immune system protects the body against infection through multiple layers of defense, including physical barriers, innate immunity, and adaptive immunity.",
		"Photosynthesis converts light energy into chemical energy stored in glucose, using carbon dioxide and water as inputs and releasing oxygen as a byproduct.",
		"Neurons communicate through synapses by releasing neurotransmitters that bind to receptors on the postsynaptic cell, transmitting electrical signals across the nervous system.",
		"Natural selection is the process where organisms with favorable traits are more likely to survive and reproduce, gradually changing the characteristics of a population.",
		"The human microbiome consists of trillions of microorganisms living in and on the human body, playing essential roles in digestion, immune function, and metabolism.",
		"Stem cells are undifferentiated cells capable of self-renewal and differentiation into specialized cell types, making them valuable for regenerative medicine.",
		"RNA interference is a biological process where small RNA molecules inhibit gene expression by destroying specific messenger RNA molecules.",
		"Hemoglobin is a protein in red blood cells that carries oxygen from the lungs to body tissues and returns carbon dioxide back to the lungs for exhalation.",
		"Epigenetics studies heritable changes in gene expression that do not involve changes to the underlying DNA sequence, often mediated by DNA methylation.",
		"The central dogma of molecular biology describes the flow of genetic information from DNA to RNA to protein through the processes of transcription and translation.",
		"Apoptosis is programmed cell death, a highly regulated process that eliminates damaged or unnecessary cells and is essential for normal development and homeostasis.",
		"Enzymes are biological catalysts that speed up chemical reactions in living organisms by lowering the activation energy required for the reaction to proceed.",
		"The blood-brain barrier is a selective membrane that separates circulating blood from the brain's extracellular fluid, protecting the brain from harmful substances.",
		"Plasmids are small circular DNA molecules found in bacteria that replicate independently of chromosomal DNA and often carry genes for antibiotic resistance.",
		"The vagus nerve is the longest cranial nerve, running from the brainstem through the chest and abdomen, regulating heart rate, digestion, and immune response.",
		"Prions are misfolded proteins that can cause normal proteins to also misfold, leading to progressive neurodegenerative diseases such as Creutzfeldt-Jakob disease.",
	}

	// Domain 4: History and culture
	historyTexts := []string{
		"The printing press, invented by Johannes Gutenberg around 1440, revolutionized the spread of knowledge by making books affordable and widely available.",
		"The Industrial Revolution began in Britain in the late 18th century, transforming manufacturing from hand production methods to machine-based processes.",
		"The Renaissance was a period of cultural, artistic, and intellectual rebirth in Europe spanning roughly from the 14th to the 17th century.",
		"The French Revolution of 1789 overthrew the monarchy and established a republic, profoundly influencing modern concepts of democracy and civil rights.",
		"Ancient Rome's engineering achievements included aqueducts, concrete construction, and road networks that connected the vast empire spanning three continents.",
		"The Silk Road was a network of ancient trade routes connecting East Asia with the Mediterranean, facilitating the exchange of goods, ideas, and cultures.",
		"The Agricultural Revolution marked the transition from nomadic hunter-gatherer societies to settled farming communities, fundamentally changing human civilization.",
		"The space race between the United States and the Soviet Union during the Cold War led to rapid advances in rocketry, satellite technology, and human spaceflight.",
		"The Columbian Exchange refers to the widespread transfer of plants, animals, diseases, and ideas between the Americas and the Old World following Columbus's voyages.",
		"Democracy originated in ancient Athens around 507 BC, where citizens could directly participate in political decision-making through assemblies and voting.",
		"The Meiji Restoration in 1868 restored imperial rule in Japan and initiated rapid modernization, transforming Japan from a feudal society into an industrial power.",
		"The Enlightenment was an intellectual movement emphasizing reason, individualism, and skepticism of traditional authority, shaping modern Western political thought.",
		"The invention of the telegraph by Samuel Morse in the 1830s enabled near-instantaneous long-distance communication for the first time in human history.",
		"The Green Revolution of the 1960s introduced high-yielding crop varieties and modern agricultural techniques, dramatically increasing food production worldwide.",
		"Ancient Egyptian civilization developed along the Nile River, creating pyramids, hieroglyphic writing, and sophisticated irrigation systems over three millennia.",
		"The Treaty of Westphalia in 1648 ended the Thirty Years' War and established the principle of state sovereignty that underpins the modern international system.",
		"The Harlem Renaissance was a cultural movement in the 1920s centered in Harlem, New York, celebrating African American literature, art, music, and identity.",
		"The fall of the Berlin Wall in 1989 symbolized the end of the Cold War and the beginning of German reunification and the collapse of communist regimes in Europe.",
		"The Magna Carta of 1215 limited the power of the English monarch and established the principle that everyone, including the king, was subject to the law.",
		"The Ming dynasty's maritime expeditions led by Zheng He in the early 15th century reached Southeast Asia, India, the Persian Gulf, and the east coast of Africa.",
	}

	// Domain 5: Technology and AI
	techTexts := []string{
		"Large language models are trained on vast amounts of text data using transformer architectures, learning to predict the next token in a sequence.",
		"Quantum computing uses quantum mechanical phenomena like superposition and entanglement to perform computations that would be infeasible for classical computers.",
		"Blockchain is a distributed ledger technology where transactions are recorded in blocks linked by cryptographic hashes, providing immutability and transparency.",
		"Retrieval-augmented generation combines a language model with a retrieval system that fetches relevant documents to ground the model's responses in factual information.",
		"Edge computing processes data near its source rather than in a centralized data center, reducing latency for applications like autonomous vehicles and IoT.",
		"Federated learning trains machine learning models across decentralized devices without sharing raw data, preserving privacy while building collective intelligence.",
		"Product quantization compresses high-dimensional vectors by splitting them into subvectors and quantizing each subspace independently, enabling efficient similarity search.",
		"Zero-knowledge proofs allow one party to prove to another that a statement is true without revealing any information beyond the validity of the statement itself.",
		"Attention mechanisms in neural networks allow models to focus on relevant parts of the input when producing output, forming the core of transformer architectures.",
		"Graph neural networks extend deep learning to graph-structured data, learning node and edge representations for tasks like social network analysis and molecular property prediction.",
		"Reinforcement learning from human feedback aligns language models with human preferences by training a reward model on human comparisons of model outputs.",
		"Homomorphic encryption allows computations to be performed on encrypted data without decrypting it, enabling secure cloud computing on sensitive information.",
		"Vector databases store and efficiently retrieve high-dimensional embeddings, enabling semantic search, recommendation systems, and retrieval-augmented generation.",
		"Diffusion models generate images by learning to reverse a gradual noising process, producing high-quality samples by iteratively denoising random noise.",
		"WebAssembly is a binary instruction format for a stack-based virtual machine, enabling near-native performance for web applications written in languages like C++ and Rust.",
		"Mixture of experts architectures route different inputs to specialized sub-networks, allowing models to scale capacity without proportionally increasing computation.",
		"Differential privacy adds calibrated noise to data or query results, providing mathematical guarantees about the privacy of individuals in a dataset.",
		"Content-addressable storage identifies data by its cryptographic hash rather than its location, enabling automatic deduplication and integrity verification.",
		"Approximate nearest neighbor search finds vectors similar to a query without exhaustive comparison, using techniques like locality-sensitive hashing or inverted file indexes.",
		"Knowledge distillation transfers learned representations from a large teacher model to a smaller student model, compressing the knowledge while maintaining performance.",
	}

	// Domain 6: Philosophy and psychology
	philTexts := []string{
		"Cognitive dissonance occurs when a person holds contradictory beliefs or when their actions conflict with their beliefs, creating psychological discomfort.",
		"The trolley problem is a thought experiment about whether it is morally permissible to divert a trolley to kill one person in order to save five others.",
		"Flow state is a mental state of complete absorption in an activity, characterized by energized focus, full involvement, and enjoyment in the process.",
		"Occam's razor suggests that among competing hypotheses, the one with the fewest assumptions should be selected, as simpler explanations are more likely to be correct.",
		"The Dunning-Kruger effect describes how people with limited knowledge in a domain tend to overestimate their competence while experts tend to underestimate theirs.",
		"Existentialism is a philosophical movement that emphasizes individual freedom, choice, and responsibility, arguing that existence precedes essence.",
		"Confirmation bias is the tendency to search for, interpret, and remember information in a way that confirms one's preexisting beliefs or hypotheses.",
		"The social contract theory proposes that individuals consent to surrender some freedoms to a governing authority in exchange for the protection of their remaining rights.",
		"Maslow's hierarchy of needs arranges human needs in a pyramid, from basic physiological needs at the base to self-actualization at the top.",
		"The prisoner's dilemma illustrates how two rational individuals might not cooperate even when it appears that it is in their best interest to do so.",
		"Stoicism teaches the development of self-control and fortitude as a means of overcoming destructive emotions, emphasizing virtue as the highest good.",
		"Heuristics are mental shortcuts that allow people to make judgments and solve problems quickly but can lead to systematic biases and errors in reasoning.",
		"The observer effect describes how the act of observation changes the phenomenon being observed, applicable in both quantum mechanics and social science.",
		"Utilitarianism holds that the best action is the one that maximizes utility, generally defined as the greatest happiness for the greatest number of people.",
		"Neuroplasticity is the brain's ability to reorganize itself by forming new neural connections throughout life, enabling learning and recovery from brain injuries.",
		"The Socratic method is a form of cooperative argumentative dialogue that stimulates critical thinking through asking and answering questions.",
		"Anchoring is a cognitive bias where initial exposure to a number or value influences subsequent judgments, even when the anchor is completely arbitrary.",
		"Determinism is the philosophical view that all events, including human actions, are ultimately determined by causes external to the will.",
		"Working memory is a cognitive system with limited capacity that temporarily holds and manipulates information, essential for reasoning, learning, and comprehension.",
		"The hedonic treadmill theory suggests that people tend to return to a relatively stable level of happiness despite major positive or negative events.",
	}

	// Domain 7: Code agent memory (closest to the product use case)
	agentTexts := []string{
		"Refactored the authentication middleware to use JWT tokens instead of session cookies, reducing server-side state and enabling horizontal scaling.",
		"Fixed a race condition in the connection pool where two goroutines could acquire the same connection simultaneously under high load.",
		"Added pagination to the user list API endpoint using cursor-based pagination instead of offset pagination for consistent results during writes.",
		"Migrated the database schema from a single users table to a normalized design with separate profiles and preferences tables.",
		"Implemented retry logic with exponential backoff for the payment gateway integration to handle transient network failures gracefully.",
		"Discovered that the memory leak was caused by goroutines blocked on a channel that was never closed when the parent context was cancelled.",
		"Upgraded the React frontend from class components to functional components with hooks, reducing the bundle size by 15 percent.",
		"Added structured logging with correlation IDs that propagate through the entire request lifecycle, from the API gateway to the database layer.",
		"Fixed a SQL injection vulnerability in the search endpoint where user input was concatenated directly into the query string.",
		"Implemented a distributed lock using Redis to prevent concurrent processing of the same job by multiple worker instances.",
		"Refactored the notification system to use a message queue instead of synchronous HTTP calls, decoupling the sender from the delivery mechanism.",
		"Added Prometheus metrics for request latency, error rates, and database connection pool utilization to improve observability.",
		"Fixed a bug where deleted users could still authenticate using cached tokens, adding a token revocation check to the validation middleware.",
		"Implemented a feature flag system that allows gradual rollout of new features to a percentage of users without requiring code deployments.",
		"Optimized the image processing pipeline by switching from synchronous resize operations to a worker pool pattern, reducing API response time.",
		"Added database query result caching using Redis with a TTL of five minutes, reducing database load by 40 percent for read-heavy endpoints.",
		"Fixed a deadlock in the inventory management system caused by concurrent transactions acquiring locks on the same rows in different orders.",
		"Implemented a circuit breaker for the external geocoding API that opens after three consecutive failures and retries after a configurable cooldown.",
		"Added end-to-end encryption for user messages using the Signal protocol, ensuring that only the sender and recipient can read the contents.",
		"Refactored the deployment pipeline to use blue-green deployments with automated health checks, reducing downtime during releases to near zero.",
	}

	// Combine all technical domains
	for _, texts := range [][]string{softwareTexts, mathTexts, bioTexts, historyTexts, techTexts, philTexts, agentTexts} {
		paragraphs = append(paragraphs, texts...)
	}

	return paragraphs
}

// extractParagraphs reads a text file and splits it into paragraphs.
// Paragraphs shorter than minLen or longer than maxLen chars are skipped.
func extractParagraphs(path string, minLen, maxLen int) []string {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil
	}
	text := string(data)
	text = strings.ReplaceAll(text, "\r\n", "\n") // normalize CRLF

	// Strip Gutenberg header/footer (between "*** START" and "*** END")
	if idx := strings.Index(text, "*** START"); idx >= 0 {
		if nl := strings.Index(text[idx:], "\n"); nl >= 0 {
			text = text[idx+nl+1:]
		}
	}
	if idx := strings.Index(text, "*** END"); idx >= 0 {
		text = text[:idx]
	}

	// Split on blank lines to get paragraphs
	blocks := strings.Split(text, "\n\n")
	var out []string
	for _, block := range blocks {
		// Clean up: collapse whitespace, trim
		p := strings.Join(strings.Fields(block), " ")
		p = strings.TrimSpace(p)
		if len(p) < minLen || len(p) > maxLen {
			continue
		}
		out = append(out, p)
	}
	return out
}

// --- Ollama embedding ---

type embedRequest struct {
	Model string   `json:"model"`
	Input []string `json:"input"`
}

type embedResponse struct {
	Embeddings [][]float32 `json:"embeddings"`
}

func embedTexts(ollamaURL, model string, texts []string, batchSize int, label string) [][]float32 {
	var all [][]float32
	client := &http.Client{Timeout: 5 * time.Minute}
	for i := 0; i < len(texts); i += batchSize {
		end := i + batchSize
		if end > len(texts) {
			end = len(texts)
		}
		batch := texts[i:end]

		body, _ := json.Marshal(embedRequest{Model: model, Input: batch})
		resp, err := client.Post(ollamaURL+"/api/embed", "application/json", bytes.NewReader(body))
		if err != nil {
			panic(fmt.Sprintf("ollama embed error: %v", err))
		}
		var result embedResponse
		if err := json.NewDecoder(resp.Body).Decode(&result); err != nil {
			panic(fmt.Sprintf("ollama decode error: %v", err))
		}
		resp.Body.Close()

		if len(result.Embeddings) != len(batch) {
			panic(fmt.Sprintf("expected %d embeddings, got %d", len(batch), len(result.Embeddings)))
		}
		all = append(all, result.Embeddings...)
		fmt.Printf("\r  %s: %d / %d embedded", label, len(all), len(texts))
	}
	fmt.Println()
	return all
}

// --- brute-force kNN ground truth ---

func bruteForceKNN(queries, base [][]float32, topK int) [][]int32 {
	gt := make([][]int32, len(queries))
	var mu sync.Mutex
	workers := runtime.GOMAXPROCS(0)
	if workers < 1 {
		workers = 1
	}
	chunk := (len(queries) + workers - 1) / workers
	var wg sync.WaitGroup
	for w := 0; w < workers; w++ {
		lo := w * chunk
		if lo >= len(queries) {
			break
		}
		hi := lo + chunk
		if hi > len(queries) {
			hi = len(queries)
		}
		wg.Add(1)
		go func(lo, hi int) {
			defer wg.Done()
			for qi := lo; qi < hi; qi++ {
				q := queries[qi]
				type sd struct {
					idx  int
					dist float64
				}
				dists := make([]sd, len(base))
				for bi, b := range base {
					dists[bi] = sd{bi, sqL2(q, b)}
				}
				sort.Slice(dists, func(a, b int) bool { return dists[a].dist < dists[b].dist })
				k := topK
				if k > len(base) {
					k = len(base)
				}
				nn := make([]int32, k)
				for i := 0; i < k; i++ {
					nn[i] = int32(dists[i].idx)
				}
				mu.Lock()
				gt[qi] = nn
				mu.Unlock()
			}
		}(lo, hi)
	}
	wg.Wait()
	return gt
}

func sqL2(a, b []float32) float64 {
	var s float64
	for i := range a {
		d := float64(a[i]) - float64(b[i])
		s += d * d
	}
	return s
}

// --- scoring ---

func scorePQ(results [][]pq.Result, gt [][]int32, R int) (recall1, inter float64) {
	var found1, interHit, interTot int
	for qi := range results {
		trueNN := int(gt[qi][0])
		truth := make(map[int]bool, R)
		for i := 0; i < R && i < len(gt[qi]); i++ {
			truth[int(gt[qi][i])] = true
		}
		for _, r := range results[qi] {
			if r.ID == trueNN {
				found1++
			}
			if truth[r.ID] {
				interHit++
			}
		}
		interTot += R
	}
	return float64(found1) / float64(len(results)), float64(interHit) / float64(interTot)
}



// scoreIVFResults builds the hash→baseIdx map once and scores all queries.
// We'll restructure to use this approach.
func scoreIVFResults(results [][]ivf.Hit, gt [][]int32, R int, hashToIdx map[uint64]int) (recall1, inter float64) {
	var found1, interHit, interTot int
	for qi := range results {
		trueNN := int(gt[qi][0])
		truth := make(map[int]bool, R)
		for i := 0; i < R && i < len(gt[qi]); i++ {
			truth[int(gt[qi][i])] = true
		}
		for _, h := range results[qi] {
			idx, ok := hashToIdx[h.Handle.Hash]
			if !ok {
				continue
			}
			if idx == trueNN {
				found1++
			}
			if truth[idx] {
				interHit++
			}
		}
		interTot += R
	}
	return float64(found1) / float64(len(results)), float64(interHit) / float64(interTot)
}

// --- helpers ---



func msPerQuery(dur time.Duration, nq int) float64 {
	return float64(dur.Microseconds()) / float64(nq) / 1000.0
}

func parseInts(csv string) []int {
	parts := strings.Split(csv, ",")
	out := make([]int, 0, len(parts))
	for _, s := range parts {
		s = strings.TrimSpace(s)
		if s == "" {
			continue
		}
		var v int
		fmt.Sscanf(s, "%d", &v)
		out = append(out, v)
	}
	return out
}

func fileExists(path string) bool {
	_, err := os.Stat(path)
	return err == nil
}

func truncStr(s string, maxLen int) string {
	s = strings.ReplaceAll(s, "\n", " ")
	if len(s) > maxLen {
		return s[:maxLen] + "..."
	}
	return s
}

// --- fvecs I/O (compatible with TEXMEX format) ---

func readFvecs(path string) [][]float32 {
	raw, err := os.ReadFile(path)
	if err != nil {
		panic(err)
	}
	var out [][]float32
	for off := 0; off < len(raw); {
		dim := int(binary.LittleEndian.Uint32(raw[off:]))
		off += 4
		v := make([]float32, dim)
		for j := 0; j < dim; j++ {
			v[j] = math.Float32frombits(binary.LittleEndian.Uint32(raw[off:]))
			off += 4
		}
		out = append(out, v)
	}
	return out
}

func writeFvecs(path string, vecs [][]float32) {
	f, err := os.Create(path)
	if err != nil {
		panic(err)
	}
	defer f.Close()
	buf := bufio.NewWriter(f)
	defer buf.Flush()
	b := make([]byte, 4)
	for _, v := range vecs {
		binary.LittleEndian.PutUint32(b, uint32(len(v)))
		buf.Write(b)
		for _, x := range v {
			binary.LittleEndian.PutUint32(b, math.Float32bits(x))
			buf.Write(b)
		}
	}
}

func readLines(path string) []string {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil
	}
	var lines []string
	scanner := bufio.NewScanner(bytes.NewReader(data))
	scanner.Buffer(make([]byte, 1024*1024), 1024*1024)
	for scanner.Scan() {
		lines = append(lines, scanner.Text())
	}
	return lines
}

func writeLines(path string, lines []string) {
	f, err := os.Create(path)
	if err != nil {
		panic(err)
	}
	defer f.Close()
	w := bufio.NewWriter(f)
	defer w.Flush()
	for _, l := range lines {
		w.WriteString(l)
		w.WriteByte('\n')
	}
}

// ivecs writer (ground truth format)
func writeIvecs(path string, vecs [][]int32) {
	f, err := os.Create(path)
	if err != nil {
		panic(err)
	}
	defer f.Close()
	buf := bufio.NewWriter(f)
	defer buf.Flush()
	b := make([]byte, 4)
	for _, v := range vecs {
		binary.LittleEndian.PutUint32(b, uint32(len(v)))
		buf.Write(b)
		for _, x := range v {
			binary.LittleEndian.PutUint32(b, uint32(x))
			buf.Write(b)
		}
	}
}

func readIvecs(path string) [][]int32 {
	raw, err := os.ReadFile(path)
	if err != nil {
		panic(err)
	}
	var out [][]int32
	for off := 0; off < len(raw); {
		dim := int(binary.LittleEndian.Uint32(raw[off:]))
		off += 4
		v := make([]int32, dim)
		for j := 0; j < dim; j++ {
			v[j] = int32(binary.LittleEndian.Uint32(raw[off:]))
			off += 4
		}
		out = append(out, v)
	}
	return out
}
